### ISSUE TITLE
Events / state?

### ISSUE THREAD

**Issue by dandv** [HubSpot/tether#103]
Would it be possible to trigger events when the tethered element goes out of bounds, or to at least inquire into the state of the element?

Use cases:

* attach to another target
* choose to scroll the parent/window instead

![image](https://cloud.githubusercontent.com/assets/33569/8799733/2a936132-2f61-11e5-9211-d46e3b37c026.png)

My particular use case is that I'm building an [on-selection menu](https://idorecall.github.io/selection-menu/). The selection [Range](https://developer.mozilla.org/en-US/docs/Web/API/Range) has an [array of ClientRects](https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects) starting from the start of the selection ("the" in the screenshot), continuing so as to cover the selected nodes, and ending with a final ClientRect ("thousand" in the screenshot). Since the selection is created `onmouseup`, it makes sense to attach a drop to the last ClientRect.

The problem is that when the user scrolls and the tether goes out of bounds, flipping it above "thousand" will obscure the selection. What I want to do is either scroll the page down, or re-attach the drop element to a different target, likely the first ClientRect of the selection.

**Comment by TrevorBurnham** [comment]
As of Tether 1.3.0, the instance object now fires an 'update' event when its attachment changes due to constraints (a088128).

**Comment by jnachtigall** [comment]
@TrevorBurnham Is there any documentation on how to listen to the 'update' event? In particular, how can I have my custom callback function being called and if so, which params are passed?

**Comment by TrevorBurnham** [comment]
```js
var tether = new Tether(...);
tether.on('update', function(event) {
  console.log(event);
});
```

The `event` object contains `attachment` and `targetAttachment` objects of the same form as those options.
