### ISSUE TITLE
HTTPS CDN hosting certificate error

### ISSUE THREAD

**Issue by dandv** [HubSpot/tether#110]
When I try to use https://github.hubspot.com/tether/dist/js/tether.js, I get a certificate warning.

![image](https://cloud.githubusercontent.com/assets/33569/9000537/a8c55bd4-36fd-11e5-8a2c-698c72dd45fd.png)

**Comment by adamschwartz** [comment]
Hey @dandv, thanks for reporting this. Did you come across this URL somewhere or were you just looking to use Tether from a CDN?

**Comment by dandv** [comment]
The user would be me. I'm building a selection menu library based on Drop, and if [this demo](https://idorecall.github.io/selection-menu/demos/iDoRecall.html) is loaded over https, it fails to load. I'm loading drop and tether in a protocol-less manner:

```html
  <script src="//github.hubspot.com/tether/dist/js/tether.js"></script>
  <script src="//github.hubspot.com/drop/dist/js/drop.js"></script>
```

![image](https://cloud.githubusercontent.com/assets/33569/9005639/9c1e0bba-3734-11e5-8afb-bff53a166dab.png)


https://github.hubspot.com/drop/docs/welcome/ also gives the security warning.

I should use CDNJS indeed.

**Comment by dandv** [comment]
Actually, I need Drop, which isn't on CDNJS. I submitted a [PR to add it to JSDelivr](https://github.com/jsdelivr/jsdelivr/pull/6207).

**Comment by adamschwartz** [comment]
I gotcha. Yeah, if that is the case, then I definitely don’t recommend https://github.hubspot.com/**/*.js. More than it doesn’t have SSL support, it’s also hosted by GitHub pages, which afaik [was not designed as a CDN](http://stackoverflow.com/a/5503156/131898). Closing as works-as-designed. :) Thanks for the PR to JSDelivr. Happy to help with adding any of HubSpot’s OS repos to CDNs.

**Comment by dandv** [comment]
@adamschwartz: Thanks. Maybe you can help with https://github.com/jsdelivr/jsdelivr/pull/6206#issuecomment-126794075 ?

**Comment by adamschwartz** [comment]
Thanks. https://github.com/jsdelivr/jsdelivr/pull/6206#issuecomment-126830891
