### ISSUE TITLE
Events/callbacks

### ISSUE THREAD

**Issue by dreadcast** [HubSpot/tether#111]
Hi there,

Do Tether provide any event/callback triggered when position of `tether-element` changes (like a tooltip that was on the right of the `target` and then is on the left because of scroll...) ?
I know css class changes, but I'd really like to be notified via a callback.

![tether](https://cloud.githubusercontent.com/assets/324253/9115158/db6a7f1e-3c5d-11e5-9294-8ed3296c4f66.png)

**Comment by dandv** [comment]
I filed the same feature request in #103.

A hacky workaround would be to watch for elements with a given CSS appearing - see The @naugtur's [insertionQ library](https://github.com/naugtur/insertionQuery), or [this jQuery plugin](http://weblog.west-wind.com/posts/2014/Oct/20/A-jquerywatch-Plugin-for-watching-CSS-styles-and-Attributes).

But really, Tether should just trigger the events.

**Comment by TrevorBurnham** [comment]
As of Tether 1.3.0, the instance object now fires an `'update'` event when its attachment changes due to constraints (https://github.com/HubSpot/tether/commit/a088128871314686b25793d706e84091a98f41d5).

**Comment by andresgutgon** [comment]
Issue related: https://github.com/HubSpot/tether/issues/277
