### ISSUE TITLE
Fallback to position: sticky on supporting browsers?

### ISSUE THREAD

**Issue by zackbloom** [HubSpot/tether#12]

**Comment by yairEO** [comment]
it depends if the browser will perform faster than Tether or not.. in many cases browsers aren't as good as pure javascript solution

**Comment by TrevorBurnham** [comment]
Still unsupported in Chrome and IE, 2 years later: http://caniuse.com/#search=sticky It would probably take a grandiose effort to make Tether achieve identical behavior with `position: sticky` anyway.
