### ISSUE TITLE
Pinning but snapped to left/middle/right attachment points?

### ISSUE THREAD

**Issue by tlrobinson** [HubSpot/tether#125]
I have a popover widget which uses `attachment: 'top center'` by default, but I would like to essentially switch to `attachment: 'top left'` or `attachment: 'top right'` if the popover content would go off-screen.

e.x.

```
|        BUTTON      |
|     +----^----+    |
|     |         |    |
|     +---------+    |

| BUTTON             |
|  +^--------+       |
|  |         |       |
|  +---------+       |

|             BUTTON |
|       +--------^+  |
|       |         |  |
|       +---------+  |
```

 `constraints` and `pin` seem like possibly the correct way to do this, but with `pin` the element become "detached" and just sticks to the side of the window, like so:

```

|             BUTTON |
|         +----^----+|
|         |         ||
|         +---------+|
```

If what I want to do is possible I haven't figured out the right combination of options. Here's a jsfiddle demonstrating the problem: https://jsfiddle.net/fwv4afkc/2/

**Comment by adamschwartz** [comment]
Thanks @tlrobinson. This is certainly a common use-case and something we would like to have better support for.

Assuming you do want the window pinning constraint, I think the difficulty is that to make this work out-of-the-box, we have to be able to essentially tether two things, the element, and its arrow. In your jsFiddle, as you drag “drag me” target off the window’s side, the arrow would have to move to stay attached to the center of the target while the element itself would be pinned to the side. Here’s an [example implementation on jsFiddle](https://jsfiddle.net/adamschwartz/rd86oe5q/).

There might be another way to accomplish what you after without the window constraint, but then as you drag the target off of the page, you’d also end up dragging the element and its arrow off the page, although the repositioning of the arrow with respect to the element could be handled as you describe.

**Comment by tlrobinson** [comment]
Thanks. Rather than have the arrow move continuously it could just have three positions: centered, and (almost) all the way to the right or left. It would be ok if the arrows and popover positioning snapped into place (possibly could be animated with CSS transitions) rather than smoothly moved, so the edge of the popover would not actually be "pinned" to the container edge (so perhaps "pin" is the wrong word for the behavior I'm looking for.

**Comment by adamschwartz** [comment]
I just noticed https://github.com/HubSpot/tether/pull/81 as well. May be of interest to you.

**Comment by yairEO** [comment]
so what is the right combination of options to achieve this? 

@geekjuice - 
Can this issue be closed btw?

**Comment by geekjuice** [comment]
If you trace the conversation back to the original [here](https://github.com/HubSpot/drop/issues/16#issuecomment-101299601), the options to make this possible are:

```javascript
tetherOptions: {
  attachment: 'top center',
  targetAttachment: 'middle center',
  constraints: [{
    to: 'window',
    attachment: 'together element'
  }]
}
```

**Comment by yairEO** [comment]
Thank you very much, I did trace it, I thought it's better to be documented here where it's more related to the subject so people will easily see code example for this extremely important fix. :+1:

**Comment by geekjuice** [comment]
Makes sense. Thanks for the bump to add that here :beers:

**Comment by th3fallen** [comment]
i know this is an older ticket but is it possible to do what he's requesting above but on a right/left basis? i have mine defaulted to right but if i cant fit i'd like to to swap if possible?
