### ISSUE TITLE
Tests with to: 'scrollParent' fail in PhantomJS

### ISSUE THREAD

**Issue by ScottTrenda** [HubSpot/tether#126]
Tested with all combinations of PhantomJS 1.9.8, PhantomJS 2.0.0, Tether 0.7.1, and Tether 1.1.0.

I get this failure stack trace when trying to test any tether with `to: 'scrollParent'` in PhantomJS and Angular:
```
	TypeError: undefined is not a constructor (evaluating 'el.getBoundingClientRect()') in /Users/scotttrenda/sportngin/team_admin/app/assets/bower_components/tether/tether.js (line 119)
		at getBounds (/Users/scotttrenda/sportngin/team_admin/app/assets/bower_components/tether/tether.js:119:38)
		at /Users/scotttrenda/sportngin/team_admin/app/assets/bower_components/tether/tether.js:1247:27
		at getBoundingRect (/Users/scotttrenda/sportngin/team_admin/app/assets/bower_components/tether/tether.js:1261:7)
		at /Users/scotttrenda/sportngin/team_admin/app/assets/bower_components/tether/tether.js:1349:35
		at forEach ([native code])
		at position (/Users/scotttrenda/sportngin/team_admin/app/assets/bower_components/tether/tether.js:1327:37)
		at position (/Users/scotttrenda/sportngin/team_admin/app/assets/bower_components/tether/tether.js:946:41)
		at position ([native code])
		at TetherClass (/Users/scotttrenda/sportngin/team_admin/app/assets/bower_components/tether/tether.js:587:18)
```

This happens because the parent element created by Angular's `$compile` ends up in a document fragment not attached to the DOM, and for some unknown reason, `getComputedStyle(document.createDocumentFragment())` returns `null` in PhantomJS, whereas it throws an error in any other browser. This, along with Tether's check for `style == null`, causes the `getScrollParent` stack to return the document fragment node as the scroll parent, and `getBoundingClientRect` does not exist on the fragment. 

This error is also easily fixed by adding a common-sense check to the parent loop in `getScrollParent`:
```
while ((parent = parent.parentNode) && parent.nodeType === 1) {
```
I assume that we only ever want elements as scroll parents. so adding that check there would prevent the `parentNode` loop from traversing up to the document node.

**Comment by spillevink** [comment]
I'm having the same issue. `&& parent.nodeType === 1` fixed it for me too.

**Comment by TrevorBurnham** [comment]
Fixed by https://github.com/HubSpot/tether/commit/1273581bfcf0a2e39d1b21fca3ecb5e4d17b04e1
