### ISSUE TITLE
Add some margin to the viewport?

### ISSUE THREAD

**Issue by FezVrasta** [HubSpot/tether#137]
In this example:

```
new Tether({
  element: yellowBox,
  target: greenBox,
  attachment: 'middle left',
  targetAttachment: 'middle left',
  constraints: [
    {
      to: 'scrollParent',
      pin: true
    }
  ]
});
```

The tooltip will stick to the border of the viewport/parent element when scrolling.

I'd like to define some margin to make it stop 10 pixels before the viewport margin.
Can I do it with Tether?

**Comment by adamschwartz** [comment]
I believe you could accomplish this by constraining it to an element upon which you set `position: fixed; top: 10px; right: 10px; bottom: 10px; left: 10px`.

**Comment by FezVrasta** [comment]
How can I do it? Reading the doc I thought it could accept only `scrollParent` or `window`...

**Comment by FezVrasta** [comment]
Ah nevermind...

```
to can be any of:

'scrollParent'
'window'
any DOM element
an array of bound points relative to the body [X1, Y1, X2, Y2]
```

**Comment by adamschwartz** [comment]
Great! Even better :+1:
