### ISSUE TITLE
Site Broken

### ISSUE THREAD

**Issue by knownasilya** [HubSpot/tether#138]
The site that has the docs and examples is broken, seems like the styles are missing.

Seeing the following in the console:

>Resource interpreted as Stylesheet but transferred with MIME type text/html: "about:blank".

**Comment by zackbloom** [comment]
Which page are you referring to? http://tether.io seems fine to me.

**Comment by knownasilya** [comment]
http://tether.io/docs/welcome/

**Comment by knownasilya** [comment]
tether.io is broken too, this is in Chrome 46.0.2490.86 (64-bit)

**Comment by zackbloom** [comment]
Any chance you're using Ghostery or a similar blocking tool?

**Comment by knownasilya** [comment]
Using "Adblock Fast", and yes it solved the issue by disabling. This shouldn't happen :smile:
