### ISSUE TITLE
What is the point of tether.css file in the dist/css?

### ISSUE THREAD

**Issue by sunny061** [HubSpot/tether#142]
Seeing as it was in the dist folder, I assumed it was required by the library. I tried to use it for some basic positioning but the "element" to attach kept on disappearing. After scratching my head for a while, I realized that the classes in the tether.css were not being toggled/used by the javascript at all and it was hiding the element for no apparent reason. Getting rid of the tether.css from my html page got the library to work as it should. So can you please at least document it somewhere that we should toggle those classes manually or just not include that CSS file. Thanks

**Comment by panzerdp** [comment]
+1 Faced the same issue. No idea why the css file is necessary, but when using it the target is hidden.

**Comment by jonagoldman** [comment]
+1

**Comment by thbar** [comment]
I'm wondering about the exact same thing. Tether is mentioned in the [twitter bootstrap rails setup](https://github.com/twbs/bootstrap-rubygem#a-ruby-on-rails) but only the JS is mentioned, and I searched quite a bit to figure out if CSS is needed at all or not.

**Comment by jnachtigall** [comment]
Bump http://stackoverflow.com/questions/36816868/which-css-files-to-include-for-tether
No reaction on this issue for almost half a year. Maybe I should be looking for an alternative...

**Comment by zackbloom** [comment]
Hi, sorry for the delay.  To the best of my knowledge none of the CSS files are required to get Tether itself to work.  They are used by various dependencies of Tether to avoid having to duplicate that code or create another `tether-css` library.
