### ISSUE TITLE
Add documentation about addTargetClasses

### ISSUE THREAD

**Issue by Sinewyk** [HubSpot/tether#146]
Found it by chance in the source code and started using it. Collaborators were wondering where it came from because it is missing from the documentation.

**Comment by ericdfields** [comment]
@Sinewyk can you elaborate? I just ran into an exception where it's trying to call 

`if (!(this.options.addTargetClasses === false)) {`

but this.options is undefined

**Comment by Sinewyk** [comment]
My issue is that the documentation is outdated, unrelated to an exception I'm afraid =).
