### ISSUE TITLE
Expose when position has been flipped?

### ISSUE THREAD

**Issue by giladgray** [HubSpot/tether#154]
When setting `attachment: 'together'` to enable the auto-flipping behavior, it seems the only way to know that the element has been flipped is by the CSS classes. The JS `tether` object has `attachment` and `targetAttachment` properties, but these reflect the original values, not the temporary "flipped" ones. 

Would it be possible to reflect the actual state of the Tether in the JS object so I could use it programmatically? 

I'm trying to update the transform-origin of the element dynamically based on a number of other factors and it works great until the element suddenly flips itself, and my code has no way of knowing when that has happened.

**Comment by TrevorBurnham** [comment]
As of Tether 1.3.1, you can now listen for an `'update'` event on the tether instance: a088128871314686b25793d706e84091a98f41d5

**Comment by giladgray** [comment]
incredible! thanks 👍
