### ISSUE TITLE
tether.js clearTimeout() error

### ISSUE THREAD

**Issue by zhangafa** [HubSpot/tether#160]
PendingTimeout is null, the implementation of the clearTimeout method, Angular2 will be reported to the error.
before:
if (typeof pendingTimeout !== 'undefined') {
      clearTimeout(pendingTimeout);
      pendingTimeout = null;
    }
after:
if (pendingTimeout !== null && typeof pendingTimeout !== 'undefined') {
      clearTimeout(pendingTimeout);
      pendingTimeout = null;
    }
..

**Comment by DiscoNova** [comment]
Calling clearTimeout with an "invalid" ID (i.e. null/undefined/"something else that is not from setTimeout()") does not have any effect, is not supposed to throw errors and should always be a safe call without any sanity checks.

Also... assigning null-value to the cleared variable seems like doing even more things that serve no actual purpose.

**Comment by TrevorBurnham** [comment]
Yeah, the code here is a little sloppy (though I have no idea what Angular2 is doing that could cause an error to be thrown here). Fixed by 4f80b74
