### ISSUE TITLE
I have a question on the use of tether

### ISSUE THREAD

**Issue by whyfind** [HubSpot/tether#161]
For example ,  see img. 
![image](https://cloud.githubusercontent.com/assets/11816904/14371549/7828bbf8-fd6b-11e5-9954-b2163a3890db.png)

when i open index.html in brower  , this can't find  ../../css/drop.css file.

![image](https://cloud.githubusercontent.com/assets/11816904/14371507/fc465a54-fd6a-11e5-9572-b3b853e30b79.png)

Then an error occurs。

![image](https://cloud.githubusercontent.com/assets/11816904/14371623/1f5817ac-fd6c-11e5-8265-6a75ef8cd856.png)

ps:I'not good at english.See the picture

**Comment by TrevorBurnham** [comment]
Unfortunately those examples are not ready-to-run. The directory structure doesn't match up with the paths in the HTML files.
