### ISSUE TITLE
Console error after update: zeroElement is not of type 'Node'

### ISSUE THREAD

**Issue by JohannUlbrich** [HubSpot/tether#168]
Hi, we use the npm module tether-drop in our angular webapp. But since the last update it uses tether 1.3.1 and now we get this console error on every page change `TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.`. But it works great with tether 1.2.2.

I guess the `destroy()`-method causes this error because it calls the internal `removeUtilElements()`-function which tries to remove a `zeroElement`, but the element isn't created at this time. Only after opening the dropdown the element exists.

**Comment by luetge** [comment]
Same here, in particular our popover only opens once, afterwards the error prevents it from opening again, we cannot use this in production like this, we would be grateful for a fix :+1:

**Comment by TrevorBurnham** [comment]
😦  I'll look into this ASAP.

**Comment by TrevorBurnham** [comment]
Fixed by 2d58e7b, which is included in the 1.3.2 release.

**Comment by luetge** [comment]
Thanks for the fast fix, awesome! :+1:

**Comment by MatiasFMolinari** [comment]
Hi, I'm having the same problem. I have it installed through the rails-assets-tether gem, which only contains the source up to 1.3.1. All the other versions I've tried give out the error.
