### ISSUE TITLE
Compatibility issue with Bootstrap v4-alpha2

### ISSUE THREAD

**Issue by crw** [HubSpot/tether#173]
Howdy! Please check out my ticket over at the Bootstrap side for more details:

https://github.com/twbs/bootstrap/issues/19843

Essentially, there was a change between tether.js v1.1.0 and v1.3.1 that caused Bootstrap's Tooltip (and other widgets) to break. 

I am not sure if this is a bug with Bootstrap's usage or with your API, so I decided to open this here to make you aware. Thanks!

**Comment by TrevorBurnham** [comment]
This sounds like the same bug described at https://github.com/HubSpot/tether/issues/168. Have you tried Tether 1.3.2, which contains the patch for that bug?

**Comment by crw** [comment]
That fixed the issue! Thanks, I will close.
