### ISSUE TITLE
Evented `off` broken?

### ISSUE THREAD

**Issue by c-dante** [HubSpot/tether#174]
Looking at the source for utils.Evented, I see this logic:

```cs
  off(event, handler) {
    if (typeof this.bindings !== 'undefined' &&
        typeof this.bindings[event] !== 'undefined') {
      return;
    }

    // ...
```
https://github.com/HubSpot/tether/blob/48209666e0ca66023730d8ef21c86a600fdd920f/src/js/utils.js#L285

This guard makes it so you can never turn "off" an event handler. Should it have instead been:
```cs
    if (typeof this.bindings === 'undefined' ||
        typeof this.bindings[event] === 'undefined') {
      return;
    }
```

Or am I missing something here?

**Comment by TrevorBurnham** [comment]
Right you are! Thanks: 7151ff5
