### ISSUE TITLE
Follow svg element?

### ISSUE THREAD

**Issue by twastvedt** [HubSpot/tether#176]
Is an element supposed to be able to follow an svg element as it moves? For example, I have a `rect` element controlled by a drag behavior in d3, which just means that d3 updates the `rect`'s `x` and `y` attributes while the mouse is dragging. Should I be able to get a tether element to follow the `rect`? Right now, it moves the tether element to the correct location when I start dragging, but then doesn't change the position after that.

**Comment by DiscoNova** [comment]
Last time I checked, tether only listens to scroll-events. Dragging (usually) does not cause those to be emitted. If the element's drag-event has some hook-point for you to attach a callback, you could possibly request tether to reposition manually using that.

**Comment by twastvedt** [comment]
Yep, ok. That's as I suspected. I just discovered `.position()` though, which does that trick. Thanks!
