### ISSUE TITLE
Tether element that targets another tether element: how to handle scroll -> position()

### ISSUE THREAD

**Issue by slorber** [HubSpot/tether#195]
I'm building an onboarding with hotpots, and when we click on the hotspot a tooltip gets displayed near the hotspot. So the hotspot is a normal tether element, and the tooltip is another tether element that targets the hotspot.

The problem is that when I scroll, the hotspot reposition itself (because there are scrollParents listeners that trigger position(), but the tooltip does not reposition itself. Obviously, as it targets the hotspot which is a tethered element, it doesn't know how to attach properly its scroll listener.

This leads to this kind of issue in my app:

![image](https://cloud.githubusercontent.com/assets/749374/17326201/0757c00e-58b0-11e6-99ec-86917422198d.png)

I'd like to have a way to detect when the hotspot repositions itself, so that it can cascade to the tooltip automatically. Some pseudo code of this kind:

```
hotspot.onPosition(() => tooltip.position());
````

Is it possible to add such a hook ?

Or maybe this could be handled directly inside the lib by detecting that a tether element (tooltip) targets another tether element (hotspot)? In which case it should be possible to add as scrollParents of the tooltip the scrollParents of the hotspot automatically

**Comment by slorber** [comment]
Also, a bit related, I'd like that if the hotspot is out of bound, then be able to hide the tooltip.

Here the hotspot has been scrolled and is hidden, but I don't really know how to make my tooltip disappear.

![image](https://cloud.githubusercontent.com/assets/749374/17327069/cf08a0aa-58b5-11e6-82f4-7f320685a385.png)

**Comment by TrevorBurnham** [comment]
I'm not familiar with "hotspots," but it sounds like this is an issue with that library, not with Tether. Right?

**Comment by slorber** [comment]
@TrevorBurnham hotspot is not a library. I'm building a hotspot system WITH tether and I am actually limited by the library

**Comment by TrevorBurnham** [comment]
Ah, I see. Instead of tethering the tooltip to the hotspot, why not tether the tooltip to whatever element the hotspot is tethered to?

**Comment by slorber** [comment]
Because I want the tooltip to be positionned relative to the hotspot and not have to sync positionning manually. Moving the hotspot position should not break tooltip positionning.

Also, the 2 tethered elements should be able to handle different constraints. My hotspot is likely to have  `{to: 'scrollParent',attachment: 'none'}` while the tooltip will have `attachment: together` so that the tooltip can "flip" around the hotspot. This seems complicated to achieve your way.  

Your solution could work but requires more work and is a bit like a workaround too.

I think it should be supported to use tether in another tether element.

Plus, I may want soon to try to add my onboarding hotspot+tooltip inside an existing dropdown, which is also a tethered element. This means 3 levels of tether :)
