### ISSUE TITLE
In utils.js zeroElement should be recreated if it no longer exists

### ISSUE THREAD

**Issue by cbxp** [HubSpot/tether#202]
How to reproduce the problem:
Delete the div with data-tether-id from body, tether can no longer position elements correctly since it thinks zeroElement still exists.

More specifically we ran into this problem when using tether with turbolinks. Turbolinks modifies document.body and tether can't handle it.

Proposed fix in utils.js getOrigin:
if (!node || !document.body.contains(node))

This fixed it for us at least.

**Comment by TrevorBurnham** [comment]
If Turbolinks can delete zeroElement, can it delete active Tethers? 😱 It seems odd to me that Tether should have to handle a scenario where an element it created was deleted by another library.

**Comment by ismaelga** [comment]
I solve this by calling `Tether.Utils.removeUtilElements()` on `"turbolinks:before-visit"`. Not sure if that function is supposed to be private, but it solved the issue I had for a couple of months. 😅

**Comment by TrevorBurnham** [comment]
Is this fixed by https://github.com/HubSpot/tether/pull/227/files?

**Comment by ismaelga** [comment]
Yes. It's the same thing. Thanks!
