### ISSUE TITLE
Remove round position in transform in #205 caused a display bug under Chrome on OS X

### ISSUE THREAD

**Issue by gucheen** [HubSpot/tether#207]
#205 have removed round position in transform.

Now when using tether in a second screen(e.g. Dell 1920x1080) of a mac with retina screen, there was a display bug of text.

Text display become a little bit blurred now. With round position value, it works well.

![image](https://cloud.githubusercontent.com/assets/1382472/18160083/40ed444a-705e-11e6-82fb-36f3a8feab36.png)

**Comment by belowfrog** [comment]
+1

**Comment by adamschwartz** [comment]
cc @TrevorBurnham

Ok, yeah, this is probably why I had @zackbloom round them before.

**Comment by TrevorBurnham** [comment]
😦 

So what's the best way to handle this? Rounding to the nearest px is incorrect on displays with >1 ppx. Suppose we round if and only if

```
window.matchMedia('only screen and (max-resolution: 1dppx)').matches
```

Would that make sense?

**Comment by adamschwartz** [comment]
That seems reasonable. Maybe also make it an option?

**Comment by b2whats** [comment]
Open issue
Bug on retina display

![image](https://cloud.githubusercontent.com/assets/6803842/19088013/f840f118-8a7c-11e6-906f-11025bbac386.png)
blue line height - 1px
