### ISSUE TITLE
Babel issues

### ISSUE THREAD

**Issue by yairEO** [HubSpot/tether#213]
I use Tether in a big bundle (generated by Gulp) and that bundles goes through Babel, and in that point, babel ruins the code:

    (function(root, factory) {
      if (typeof define === 'function' && define.amd) {
        define(factory);
      } else if (typeof exports === 'object') {
        module.exports = factory(require, exports, module);
      } else {
        root.Tether = factory();
      }
    }(this, function(require, exports, module) { // babel outputs: })(undefined, function (require, exports, module) {

**Comment by adleviton** [comment]
I had this happen. Any fix?
