### ISSUE TITLE
Performance is `null`

### ISSUE THREAD

**Issue by PepijnSenders** [HubSpot/tether#217]
I've been tracking my application's errors in a production state and I've been seeing this error pop up every now and then:

```
performance is null
```

The browser specs are:

```
Firefox 48.0
Mac OS X 10.10
```

I haven't taken the time to reproduce this bug, but it seems pretty obvious that in firefox `performance` can actually be `null`. Could you please check this out, the corresponding piece of code can be found here: https://github.com/HubSpot/tether/blob/master/src/js/tether.js#L50.

**Comment by PepijnSenders** [comment]
Actually it's supposed to be a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=818779. I'll leave it up to you guys, if you want to fix it or not, but an extra `&& performance` would already do the trick.

**Comment by jony89** [comment]
I'm getting  the same error on other devices as well

> Uncaught TypeError: Object [object Performance] has no method 'now' 

Android Browser 4 on Android (Jelly Bean)
Samsung Galaxy S III (GT-I9300)

**Comment by alexbardas** [comment]
@TrevorBurnham, can you please publish a new npm version that includes this fix?

**Comment by mogelbrod** [comment]
The updated check is throwing the following error in Safari v.9.1.3:
`ReferenceError: Can't find variable: performance`

Maybe switch to the following?
`typeof performance === 'object' && typeof performance.now === 'function'`

**Comment by jony89** [comment]
are you getting this with my fix as well?

**Comment by mogelbrod** [comment]
I'm getting the error the current master (`if (performance && performance.now)`)

Thanks for the quick response!

**Comment by jony89** [comment]
Still, are you able to reproduce it and fix it ? or you getting it from one of the users?

because the error u r getting is totally different 

> ReferenceError: Can't find variable: performance

vs what we actually discussed here

> Uncaught TypeError: Object [object Performance] has no method 'now'

**Comment by mogelbrod** [comment]
The error is being reported to us via [Sentry](sentry.io) with the first occurrence on Nov 15th, which is around the same time we bumped `tether` to v1.4.1.

My suggested solution would be to overwrite the `performance && performance.now` line(s) with 
`typeof performance === 'object' && typeof performance.now === 'function'`,
since typeof checks don't throw ReferenceError if the variable doesn't exist.

**Comment by jony89** [comment]
seems fine to me. create a PR for this and notify @TrevorBurnham
