### ISSUE TITLE
When dynamic content added attachment point changes

### ISSUE THREAD

**Issue by dhawalbhanushali** [HubSpot/tether#223]
When dynamic content is added in attachment(popover in my case), the attachment points changes.
Is this the desired behaviour?  I can see that `transform` in css does not change when content dynamically added.

**Comment by TrevorBurnham** [comment]
Tether does not reposition itself in response to content changes, only to `scroll` and `resize` events. You must manually reposition the Tether (using `.position()`) when you make a content change that potentially alters its dimensions.

**Comment by dhawalbhanushali** [comment]
Okay. Do I need to pass any arguments or just call the function? Also can tether object be accessed using DOM element selector?

**Comment by TrevorBurnham** [comment]
No arguments:

```
tether = new Tether(options);
// When its content changes
tether.position();
```

You need to store the `tether` reference yourself; you can't get it through the DOM.

**Comment by dhawalbhanushali** [comment]
Alright! Thank you so much. Closing this now.
