### ISSUE TITLE
Hide element when target is hidden

### ISSUE THREAD

**Issue by MikeDevice** [HubSpot/tether#254]
Let's imagine there is a dropdown, based on `tether`. It has button that opens and closes dropdown content. This button can be visible on the page or not. It depends of external conditions. We open dropdown content and after some seconds this button has been disappearing, but dropdown content is still visible, because It doesn't know about button, its target.
So how about realize this?

**Comment by TrevorBurnham** [comment]
I don't think this is possible without using [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver), which is beyond the scope of what Tether does.
