### ISSUE TITLE
Popups don't appear when fullscreen

### ISSUE THREAD

**Issue by xastor** [HubSpot/tether#266]
I'm using tether for a menu popup but when my application goes fullscreen, the tether popups don't appear anymore because they are placed outside my application by tether and so are not visible fullscreen. 

Is there a solution to this within the tether library?

**Comment by TrevorBurnham** [comment]
Tether listens for the `scroll` and `resize` events. I'd expect going fullscreen to trigger a `resize` event; is that not the case? What about [`fullscreenchange`](https://developer.mozilla.org/en-US/docs/Web/Events/fullscreenchange)? Try this:

```js
document.addEventListener('fullscreenchange', () => Tether.position());
```
