### ISSUE TITLE
Is tether connected to scroll event?

### ISSUE THREAD

**Issue by prajapati-parth** [HubSpot/tether#270]
Hello,
I'm using tether along with my react components and it works great as far as position is concerned.

But the DOM element that I specify to the `element` remains hidden until a scroll is done. As I said the position is perfect but the element is visible only after a horizontal or vertical scroll event of the browser is fired!

Thanks.

**Comment by TrevorBurnham** [comment]
Yes, Tether recalculates position when a `scroll` event occurs. If you need to force that calculation, you can call `window.Tether.position()`.

**Comment by prajapati-parth** [comment]
Wow! This is gonna solve a lot of my issues. Thanks.
