### ISSUE TITLE
SVG DOM Support

### ISSUE THREAD

**Issue by brettlaforge** [HubSpot/tether#47]
When using a SVG element as the target for tethering, the library doesn't quite work. This is due to the differences in the SVG DOM vs the HTML DOM.

It seems that in some browsers, an SVG element's classname is not guaranteed to be a string, sometimes it is [object SVGAnimatedStringPrototype]. Therefore the removeClass utility doesn't work as expected and produces the error:

TypeError: Object doesn't support property or method 'replace'.

I've got tether to work with SVG elements by changing the one line in the removeClass method from referencing the el.className to using el.getAttribute('class').

Information:
http://stackoverflow.com/questions/3294553/jquery-selector-svg-incompatible
http://toddmotto.com/hacking-svg-traversing-with-ease-addclass-removeclass-toggleclass-functions/

**Comment by smashmiek** [comment]
Hi, is there any chance that this could be rolled into the official Tether? I'm getting this issue with SVG.

**Comment by cvrebert** [comment]
Hasn't this been fixed by #48?
