### ISSUE TITLE
Does not work in "use strict" mode

### ISSUE THREAD

**Issue by jinder** [HubSpot/tether#53]
I've been looking through an issue with TetherJS that occurs only when I minify and combine my script files.  Initially, I thought it was a problem with the minification process, but I think it's caused by "use strict" mode triggering.  

The Tether JS 0.6.5 file uses 'this' in a global context, which in strict mode is undefined.  See this StackOverflow post: http://stackoverflow.com/questions/9822561/why-is-this-in-an-anonymous-function-undefined-when-using-strict

**Comment by treshugart** [comment]
It's because they have several IIFEs and they only bind the global context to the first one. In non-strict mode the context is passed on. In strict mode it is not. Another way you can solve this is to remove `"use strict"` from your compiled source.

**Comment by geekjuice** [comment]
This should be fixed with version 1. If this is still an issue though, feel free to reopen
