### ISSUE TITLE
TypeScript definitions?

### ISSUE THREAD

**Issue by estaylorco** [HubSpot/tether#58]
Hello All,

Are there any plans in the near future to get a TypeScript def file up on DefinitelyTyped?

Thank you.

**Comment by adidahiya** [comment]
lucky for you, I wrote them a few weeks ago: https://github.com/borisyankov/DefinitelyTyped/tree/master/tether

**Comment by geekjuice** [comment]
Appears to be resolved

**Comment by Delagen** [comment]
@ types/tether differ than available through this. So I think it must merged.
no module declaration!!!
