### ISSUE TITLE
Tethering to an element with multiple scrollable parents

### ISSUE THREAD

**Issue by DiscoNova** [HubSpot/tether#62]
I came across a situation where the element I want to tether has multiple scroll parents. Event listener is bound to the first one found and naturally does not receive events from other parents.

A simplified example of the issue can be seen in http://jsfiddle.net/mchc2tny/3/
- vertical scrolling of "#inner"-div works, but...
- horizontal scrolling of "#outer"-div does not

Amendment: The above is with Google Chrome 35.0.1916.114 ... with Firefox 29.0, the tethered element seems to receive absolutely no scroll-events :(

**Comment by dandv** [comment]
The fiddles need to be adjusted now that http://tether.io/tether.js is no longer the recommended way of including the library. [jsdelivr is](http://cdn.jsdelivr.net/tether/1.1.0/tether.min.js).

**Comment by DiscoNova** [comment]
Hmm... I think I created my fiddle as anonymous user, so I'm unable to claim ownership and modify it :(

**Comment by akman003** [comment]
@ibash 's code fixed my issue. I had two vertical scroll parents, neither of which were `<body>`. Thank you! And thanks to @DiscoNova for reporting it.
