### ISSUE TITLE
Remove almost never used Evented

### ISSUE THREAD

**Issue by g00fy-** [HubSpot/tether#63]
[Evented](https://github.com/HubSpot/tether/blob/2bc51f7979c1e8769356dfaa02e54d0dc50392c7/tether.js#L273) is obsolete and never used by `Tether` itself. So there is point having it in the main codebase.

It seems that the [only place when `Evented` is used](https://github.com/HubSpot/tether/search?utf8=%E2%9C%93&q=Evented)  is drop. It maybe also used in some other *libs* that extend/depend on `Tether`.

`Evented` has no usefull features, - it does not even provide things like  `event.preventDefault()` or `event.stopPropagation`.

The provided by `Evented` functionality can be easily implemented in using native [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent) on `target`

**Using `DOM` as `EventBus` would provide a more advanced solution**.

It seems reasonable to remove `Evented` from the codebase - if that is not possible because of some legacy code or *libs* depending on this functionality - I suggest replacing it with implementation based on `CustomEvent` ( polyfill may be included for legacy browser )

**Comment by geekjuice** [comment]
`Evented` is used a simple event handler and serves as a base for `drop`, `tooltip`, `shepherd`, and `select`. To say it has no useful features a bit unfair given how useful they are in these libraries. If you still think otherwise, you're welcome to start a pull request with a possible solution.
