### ISSUE TITLE
Browserify or Node: Error: Cannot find module 'tether'

### ISSUE THREAD

**Issue by kimmobrunfeldt** [HubSpot/tether#70]
Trying to `var Tether = require('tether');` and build with browserify, produces this error: `Error: Cannot find module 'tether'`

In node_modules/tether/package.json, there is no "main" key which would indicate where to look for a file. This is why browserify/node can't find any file matching name "tether"

Here is the most minimal setup to reproduce the problem: https://github.com/kimmobrunfeldt/tether-browserify-bug

**Comment by kimmobrunfeldt** [comment]
Related to https://github.com/HubSpot/tether/pull/68

**Comment by davekiss** [comment]
Getting this same error here too, but the package.json file does indeed specify the `main` key.

**Comment by geekjuice** [comment]
The version of `tether` included in your project is `0.6.5` which did not have the `main` field in the `package.json` resulting in the error you are seeing. For some reason, `^0.6.5` in your `package.json` doesn't seem to bump tether to version `>0.6.5` which is what I expected, but as long as you specifiy a version `>=0.7.0`, it should work.

**Comment by davekiss** [comment]
@geekjuice still getting this with 0.7.2, so I must be doing something wrong. See something glaring in my package.json?

```
{
  "main": "app.js",
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browser": {
    "backbone.supermodel" : "../bower_components/backbone.supermodel/index.js",
    "magnific-popup"      : "../bower_components/magnific-popup/dist/jquery.magnific-popup.min.js",
    "tether"              : "../bower_components/tether/tether.min.js",
    "tether-drop"         : "../bower_components/tether-drop/dist/js/drop.min.js",
    "tether-tooltip"      : "../bower_components/tether-tooltip/dist/js/tooltip.min.js"
  },
  "browserify-shim": {
    "jquery"              : "global:jQuery",
    "backbone"            : "global:Backbone",
    "underscore"          : "global:_",
    "rivets"              : "global:rivets",
    "backbone.supermodel" : "Backbone.SuperModel",
    "magnific-popup"      : "jQuery.magnificPopup",
    "tether"              : "Tether",
    "tether-drop"         : "Drop",
    "tether-tooltip"      : "Tooltip"
  },
  "devDependencies": {
    "browserify": "^10.2.3",
    "browserify-shim": "^3.8.7"
  }
}
```

**Comment by geekjuice** [comment]
Could it be because you have your `bower_components` directory a level above where your `package.json` is? When I have my `bower_components`, `node_modules`, and `package.json` all on the same level, I run into no issues, but if I structure the directory like how you have it, I get [this error](https://github.com/thlorenz/browserify-shim/issues/61).

**Comment by davekiss** [comment]
@geekjuice argh. sure was. thanks for helping with that. hopefully this helps someone else.

**Comment by geekjuice** [comment]
No problem :smile_cat:

**Comment by mitogh** [comment]
Thank you @davekiss that work for me ;)
