### ISSUE TITLE
Created NuGet package

### ISSUE THREAD

**Issue by sonnylegreat** [HubSpot/tether#89]
Hi there, I created a NuGet package for your project, let me know if you'd like anything changed.

https://www.nuget.org/packages/HubSpot.Tether/

**Comment by geekjuice** [comment]
Is there a reason the version on NuGet is different from the package version which is currently `v0.7.2`?

**Comment by sonnylegreat** [comment]
My apologies, fixed.

**Comment by geekjuice** [comment]
Related https://github.com/HubSpot/shepherd/issues/68
