### ISSUE TITLE
No longer support IE9?

### ISSUE THREAD

**Issue by matbrady** [HubSpot/tether#95]
I noticed this issue while using [Select.js](http://github.hubspot.com/select/docs/welcome/). Tether fails to correctly apply class names. I'm guessing the error is related to the [utility functions](https://github.com/HubSpot/tether/blob/master/src/js/utils.js#L191-L211). 

![tether_bug](https://cloud.githubusercontent.com/assets/1770862/8619291/d218cad6-26e3-11e5-916f-f26886d91712.png)

**Comment by woble** [comment]
Has to do with the switch to ECMAScript 6. Only IE11 supports it, and by far not everything.

http://kangax.github.io/compat-table/es6/

Function in question: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const

Sticking to 0.7.* for now.

**Comment by geekjuice** [comment]
The issue should be fixed if you upgrade to `tether@1.0.3`.

@woble While it is due to the switch to ES6, it was actually just programmer error on my part. We use Babel to transpile ES6 to ES5
